"""Generate explicit GBA 4bpp overworld tiles from the original atlas."""
from pathlib import Path
import re

source = Path("src/data/gfx_overworld.c")
output = Path("src/data/gfx_overworld_color.c")
text = source.read_text(encoding="utf-8-sig")
body = text[text.index("{") + 1:text.rindex("}")]
words = [int(value, 16) for value in re.findall(r"0x[0-9A-Fa-f]+", body)]
if len(words) != 96 * 8:
    raise SystemExit(f"expected 768 tile words, found {len(words)}")

def convert_word(word):
    result = 0
    for shift in range(0, 32, 4):
        index = (word >> shift) & 0xF
        if index == 0:
            index = 1
        result |= index << shift
    return result

converted = [convert_word(word) for word in words]
lines = [
    '#include "gba.h"',
    '',
    '// Generated by tools/convert_overworld_tiles.py.',
    '// Geometry is unchanged; opaque BG tiles reserve color ID 0.',
    'const u32 g_overworld_color_tiles[] = {',
]
for index in range(0, len(converted), 8):
    lines.append("    " + ",".join(f"0x{word:08X}" for word in converted[index:index + 8]) + ",")
lines += ['};', 'const u32 g_overworld_color_tile_count = 96;', '']
output.write_text("\n".join(lines), encoding="ascii")
